runtime: go111

handlers:
- url: /watches/.*
  script: auto
  secure: always

- url: /patients/.*
  script: auto
  secure: always

- url: /wearlogs/.*
  script: auto
  secure: always


env_variables:
  MY_VAR: "my-var"